- import_tasks: kubeadm_config.yml

# NOTE: this is required for the next template task
# since it iterates over controller network facts
- name: gather facts about primary controller node
  ansible.builtin.setup:
    gather_subset: network
  delegate_facts: true
  delegate_to: "{{ groups['master'][0] }}"

- name: kubeadm join worker
  ansible.builtin.command: >
    kubeadm join {{ control_plane_endpoint }}
      --config /var/lib/kubeadm/config.yaml
  become: true
  register: kubeadm_join_result
  vars:
    controller: "{{ groups['master'][0] }}"

- name: print kubeadm join result
  ansible.builtin.debug:
    var: kubeadm_join_result.stdout_lines
