- name: unhold k8s packages
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: install
  loop:
    - kubeadm
    - kubectl
  become: true

- name: upgrade k8s packages
  ansible.builtin.apt:
    name:
      - kubeadm={{ kubernetes_version }}*
      - kubectl={{ kubernetes_version }}*
    update_cache: true
  become: true

- name: hold k8s packages
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubeadm
    - kubectl
  become: true
