- name: get kubectl version
  ansible.builtin.command: >
    kubectl version
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  become: true
  changed_when: false
  register: kubectl_version
  when: inventory_hostname in groups['master'][0]

- include_tasks: "{{ action }}.yml"
